name: Baby Forex
favicon: null
layout_spectrum: 0.06227865372784436
typography_spectrum: 0.021234963089227676
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7034455167595297
  lightness: 0.12702174833975732
  saturation: 0.2588448631577194
  rhythmicContrast: 0.8270894694142044
purpose: []
