name: Baby Forex
favicon: null
layout_spectrum: 0.87772
typography_spectrum: 0.90713
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#778899'
    - '#00ff00'
    - '#ff0000'
  brandStrength: 0.7034455167595297
  lightness: 0.12702174833975732
  saturation: 0.2588448631577194
  rhythmicContrast: 0.8270894694142044
purpose: []
